### PR TITLE
Drop kde own name

### PR DESCRIPTION
**Pull request by bbhtt**
Needs testing.

### CODE REVIEW

**Comment by bbhtt** [comment]
Testing needed because I don't see any tray related settings.

**Comment by bbhtt** [comment]
> So, did you test it?

I couldn't find a way to enable the tray https://github.com/flathub/re.chiaki.Chiaki/pull/19#issuecomment-1739380262

**Comment by bbhtt** [comment]
Then what is this permission for?

**Comment by bbhtt** [comment]
> Then what is this permission for?

cc @AsciiWolf any idea, you seem to have added this app.


I can check if it is being used for anything else later.

**Comment by bbhtt** [comment]
> I don't know; it was already there the first time I touched this manifest, and I didn't bother.  I assumed you knew what it was for, given that you seemed to know it was safe to remove 🤷🏿 

I assumed it was for tray, given all the other applications used it exactly for that.

In any case such a wildcard access should never be used.

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
> I don't think I'd like to remove it blindly, without having at least some idea of why it was there.

From a look, I don't see it being used for anything. I'll update it accordingly

Hopefully the @AsciiWolf or @thestr4ng3r can clarify, since they submitted the app to flathub and merged the upstream flatpak manifest. https://github.com/flathub/re.chiaki.Chiaki/pull/19#issuecomment-1745314191

**Comment by bbhtt** [comment]
> @bbhtt So did you?

I don't have a playstation to test with. If someone has it please do.

**Comment by swsnr** [comment]
I think I'll just close this then.   As said before I don't see any security implication with the current permissions, and hence no pressing need to change this.

I'm sorry, but you want to have this changed, so the onus to test it and demonstrate that the change is good lies with you.

**Comment by bbhtt** [comment]
What's the point to close this? Someone else can test this.

**Comment by bbhtt** [comment]
> security implication with the current permissions, and hence no pressing need to change this.

sooner or later we'll land https://github.com/flathub/flatpak-builder-lint/pull/114 it's going to be treated as an error then and builds won't pass

**Comment by bbhtt** [comment]
> the onus to test it and demonstrate that the change is good lies with you.

Yes, but the onus lies equally on you since you are the maintainer.

**Comment by swsnr** [comment]
> What's the point to close this? 

That it goes away from the list of open MRs on my frontpage.  Everyone can still see it if it's closed, but as things stand it's not actionable to us as maintainers.

I'm not closing it again, and and please, do not reopen it again.

> sooner or later this is going to land https://github.com/flathub/flatpak-builder-lint/pull/114. Then it's going to be treated as an error then and builds won't pass. It's going to become relevant.

Then I may take time to look at it 🤷🏿 Or I may not and wait still someone else cares enough to actually take a good look and test the change 🤷🏿 

> Yes, but the onus lies equally on you too since you are the maintainer.

My time is my own to spend however I like, and I am in no way obliged to test changes you make to this repo.

**Pull request closed without merging**
