### PR TITLE
Fixing some Wayland issues

### PR DESCRIPTION
**Pull request by iMonZ**
Fixed https://github.com/flathub/re.chiaki.Chiaki/issues/3

### CODE REVIEW

**Comment by AsciiWolf** [comment]
https://github.com/flathub/re.chiaki.Chiaki/issues/3#issuecomment-1006952004

**Comment by lunaryorn** [comment]
I'm using the corresponding overrides `flatpak override --user --socket=wayland --socket=fallback-x11 --nosocket=x11 re.chiaki.Chiaki` since some time and did not have any issues.

**Comment by AsciiWolf** [comment]
Are you using GNOME? I had several glitches and weird behavior when running Chiaki on native Wayland.

**Comment by lunaryorn** [comment]
I'm using Gnome.

What kind of glitches did you see? Perhaps I just didn't notice 🤷

**Comment by AsciiWolf** [comment]
I don't have my PS4 anymore so I can't re-test it, but I remember that there was some window decoration issue that was pretty annoying, keyboard/mouse input issues and also some flickering during the streaming. It is possible that these issues got fixed by GNOME/XWayland devs or by switching to a newer runtime, sadly I am unable to confirm this with my current (PC + Nintendo Switch, no PS4/PS5) setup.

**Comment by AsciiWolf** [comment]
By the way, if anyone is interested in helping me co-maintain this repository, feel free to let me know. I am the only maintainer and as I said, I sadly do not have my PS4 anymore.

**Comment by iMonZ** [comment]
> By the way, if anyone is interested in helping me co-maintain this repository, feel free to let me know. I am the only maintainer and as I said, I sadly do not have my PS4 anymore.

I could help you out. I have a PS5 to test.

**Comment by iMonZ** [comment]
> I don't have my PS4 anymore so I can't re-test it, but I remember that there was some window decoration issue that was pretty annoying, keyboard/mouse input issues and also some flickering during the streaming. It is possible that these issues got fixed by GNOME/XWayland devs or by switching to a newer runtime, sadly I am unable to confirm this with my current (PC + Nintendo Switch, no PS4/PS5) setup.

Let me check with the latest version

**Comment by lunaryorn** [comment]
I could help too, if you like.

**Comment by lunaryorn** [comment]
@AsciiWolf I haven't yet heard anything. Should we perhaps open an issue about additional maintainers at <https://github.com/flathub/flathub/>?

Meanwhile, can we merge this?  I haven't had any wayland issues with Chiaki.  @iMonZ, were you able to test chiaki with wayland meanwhile?

**Comment by AsciiWolf** [comment]
I have contacted @barthalion via e-mail. Sure, feel free to merge it if Chiaki works without issues on both (latest 42/43) GNOME and (LTS and latest stable) KDE Wayland sessions.

**Comment by lunaryorn** [comment]
@iMonZ I've been granted write access to this repository; should I merge this MR?

**Comment by AsciiWolf** [comment]
Feel free to, if it actually works fine for you (on both GNOME and KDE wayland sessions).

**Comment by swsnr** [comment]
I've tested it a lot on Gnome, simply by playing a lot 😇 but not under KDE; I do not use KDE and don't really have time to explicitly test it 🤷🏿 

I'd merge nonetheless, because as far as I can see wayland support in KDE is still not complete (see e.g. <https://community.kde.org/Plasma/Wayland_Showstoppers>) and wayland sessions still don't seem to be the default in KDE.  So if issues appear I'd expect that users just go back to X11 or just open an issue here 🙂

**Comment by iMonZ** [comment]
> I've tested it a lot on Gnome, simply by playing a lot 😇 but not under KDE; I do not use KDE and don't really have time to explicitly test it 🤷🏿
> 
> I'd merge nonetheless, because as far as I can see wayland support in KDE is still not complete (see e.g. https://community.kde.org/Plasma/Wayland_Showstoppers) and wayland sessions still don't seem to be the default in KDE. So if issues appear I'd expect that users just go back to X11 or just open an issue here 🙂

That's why I used wayland and fallback-x11 which means if flatpak detects wayland it uses wayland if it detects x11 it switches back to x11 :)

**Comment by swsnr** [comment]
Had to revert this, see #8 and #11.   I've opened https://github.com/flathub/re.chiaki.Chiaki/issues/12 to reconsider this in a year or so.

**Pull request merged**
