### PR TITLE
Update modules and build setup

### PR DESCRIPTION
**Pull request by swsnr**
- [x]  Use cmake-ninja as build system; it's faster and seems to be generally preferred these days.
- [x] Use ffmpeg runtime extension instead of bundling ffmpeg
- [x] Update protobuf library

### CODE REVIEW

**Comment by swsnr** [comment]
@Daniel6372 This is where you could help me with testing, but it's not complete yet (see the checkboxes in the original comment).  I'll ping you when I'm done, but could take a few days (got to get all my Christmas presents first, so I'll be busy the next days 😬 ).

**Comment by swsnr** [comment]
@Daniel6372 These changes turned out to be easier than anticipated, so this would be ready for testing already 😇 

Would you mind to give it a try?

**Comment by swsnr** [comment]
@Daniel6372 I've found an error in the builds; please wait for the current test build 12783 and try that one.  12780 won't start.

**Comment by Daniel6372** [comment]
Same error as 12780
`bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256`

**Comment by swsnr** [comment]
@Daniel6372 Yeah, so it already.  That was a somewhat stupid typo.  It's getting late here 🙈 

I've pushed again; let's see whether it works now. 

I'm off now; I'll continue this tomorrow or Thursday.

**Comment by Daniel6372** [comment]
With the exception of wayland, everything works great for me.
This is the message that gets written when I fullscreen the remote play window:
`qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

**Comment by swsnr** [comment]
I don't think that's related; I see this message in windowed mode too, and it just says that wayland clients can't force windows into focus.

**Comment by swsnr** [comment]
@Daniel6372 Does hardware decoding work for you?  I.e. vaapi?  I can't test it currently, because I'm affected by https://github.com/intel/media-driver/issues/1371 meaning it's generally broken for me here.

**Comment by Daniel6372** [comment]
@swsnr vaapi does work, verified using intel-gpu-top

**Comment by swsnr** [comment]
@Daniel6372 Thanks a lot for your help 🙏🙏

@AsciiWolf @iMonZ I think this is ready for review, if you'd like to take a look

**Comment by AsciiWolf** [comment]
It looks good. However I am not able to provide a proper review since I don't have my PS4 anymore and can't test the actual functionality of the new Chiaki build.

**Comment by swsnr** [comment]
@AsciiWolf Thanks for taking a look; I tested it and so did @Daniel6372  so I think this is safe to be merged.

**Pull request merged**
